<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.unrc.app.TestSuite" time="0.471" tests="13" errors="12" skipped="0" failures="0">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386"/>
    <property name="java.vm.version" value="20.0-b12"/>
    <property name="java.vm.vendor" value="Sun Microsystems Inc."/>
    <property name="java.vendor.url" value="http://java.sun.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="OpenJDK Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/karim/Anonymous/Proyecto"/>
    <property name="java.runtime.version" value="1.6.0_27-b27"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-6-openjdk-i386/jre/lib/endorsed"/>
    <property name="os.arch" value="i386"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Sun Microsystems Inc."/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/home/karim/Workspace/.metadata/.plugins/org.eclipse.m2e.core/launches/m2conf3504146795939907123.tmp"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/server:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386:/usr/lib/jvm/java-6-openjdk-i386/jre/../lib/i386:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/client:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386::/usr/java/packages/lib/i386:/usr/lib/i386-linux-gnu/jni:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/lib/jni:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="50.0"/>
    <property name="sun.management.compiler" value="HotSpot Tiered Compilers"/>
    <property name="os.version" value="3.2.0-23-generic"/>
    <property name="user.home" value="/home/karim"/>
    <property name="user.timezone" value="America/Argentina/Cordoba"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.6"/>
    <property name="user.name" value="karim"/>
    <property name="java.class.path" value="/home/karim/.eclipse/org.eclipse.platform_3.7.0_155965261/configuration/org.eclipse.osgi/bundles/430/1/.cp/jars/plexus-classworlds-2.4.jar"/>
    <property name="java.vm.specification.version" value="1.0"/>
    <property name="sun.arch.data.model" value="32"/>
    <property name="java.home" value="/usr/lib/jvm/java-6-openjdk-i386/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher -B install"/>
    <property name="java.specification.vendor" value="Sun Microsystems Inc."/>
    <property name="user.language" value="en"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.6.0_27"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-6-openjdk-i386/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-6-openjdk-i386/jre/lib/resources.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/rt.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/jsse.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/jce.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/charsets.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/netx.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/plugin.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/rhino.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/lib/modules/jdk.boot.jar:/usr/lib/jvm/java-6-openjdk-i386/jre/classes"/>
    <property name="java.vendor" value="Sun Microsystems Inc."/>
    <property name="maven.home" value="/home/karim/Anonymous/Proyecto/EMBEDDED"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://java.sun.com/cgi-bin/bugreport.cgi"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="testTest" classname="com.unrc.app.InmoTest" time="0"/>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.UserSpec" time="0.195">
    <error message="com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database &apos;inmoapp_development_test&apos;" type="org.javalite.activejdbc.InitException"><![CDATA[org.javalite.activejdbc.InitException: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database 'inmoapp_development_test'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:812)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3269)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1182)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2670)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at org.javalite.activejdbc.DB.open(DB.java:64)
	at org.javalite.activejdbc.Base.open(Base.java:51)
	at com.unrc.app.UserSpec.before(UserSpec.java:16)
]]></error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.UserSpec" time="0.198">
    <error message="Cannot rollback transaction, connection &apos;default&apos; not available" type="org.javalite.activejdbc.DBException">org.javalite.activejdbc.DBException: Cannot rollback transaction, connection 'default' not available
	at org.javalite.activejdbc.DB.rollbackTransaction(DB.java:587)
	at org.javalite.activejdbc.Base.rollbackTransaction(Base.java:296)
	at com.unrc.app.UserSpec.after(UserSpec.java:22)
</error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.OwnerSpec" time="0.01">
    <error message="com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database &apos;inmoapp_development_test&apos;" type="org.javalite.activejdbc.InitException"><![CDATA[org.javalite.activejdbc.InitException: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database 'inmoapp_development_test'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:812)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3269)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1182)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2670)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at org.javalite.activejdbc.DB.open(DB.java:64)
	at org.javalite.activejdbc.Base.open(Base.java:51)
	at com.unrc.app.OwnerSpec.before(OwnerSpec.java:16)
]]></error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.OwnerSpec" time="0.01">
    <error message="Cannot rollback transaction, connection &apos;default&apos; not available" type="org.javalite.activejdbc.DBException">org.javalite.activejdbc.DBException: Cannot rollback transaction, connection 'default' not available
	at org.javalite.activejdbc.DB.rollbackTransaction(DB.java:587)
	at org.javalite.activejdbc.Base.rollbackTransaction(Base.java:296)
	at com.unrc.app.OwnerSpec.after(OwnerSpec.java:22)
</error>
  </testcase>
  <testcase name="shouldSaveRecord" classname="com.unrc.app.OwnerSpec" time="0.001">
    <error message="com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database &apos;inmoapp_development_test&apos;" type="org.javalite.activejdbc.InitException"><![CDATA[org.javalite.activejdbc.InitException: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database 'inmoapp_development_test'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:812)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3269)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1182)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2670)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at org.javalite.activejdbc.DB.open(DB.java:64)
	at org.javalite.activejdbc.Base.open(Base.java:51)
	at com.unrc.app.OwnerSpec.before(OwnerSpec.java:16)
]]></error>
  </testcase>
  <testcase name="shouldSaveRecord" classname="com.unrc.app.OwnerSpec" time="0.002">
    <error message="Cannot rollback transaction, connection &apos;default&apos; not available" type="org.javalite.activejdbc.DBException">org.javalite.activejdbc.DBException: Cannot rollback transaction, connection 'default' not available
	at org.javalite.activejdbc.DB.rollbackTransaction(DB.java:587)
	at org.javalite.activejdbc.Base.rollbackTransaction(Base.java:296)
	at com.unrc.app.OwnerSpec.after(OwnerSpec.java:22)
</error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.BuildingSpec" time="0.004">
    <error message="com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database &apos;inmoapp_development_test&apos;" type="org.javalite.activejdbc.InitException"><![CDATA[org.javalite.activejdbc.InitException: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database 'inmoapp_development_test'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:812)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3269)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1182)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2670)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at org.javalite.activejdbc.DB.open(DB.java:64)
	at org.javalite.activejdbc.Base.open(Base.java:51)
	at com.unrc.app.BuildingSpec.before(BuildingSpec.java:16)
]]></error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.BuildingSpec" time="0.005">
    <error message="Cannot rollback transaction, connection &apos;default&apos; not available" type="org.javalite.activejdbc.DBException">org.javalite.activejdbc.DBException: Cannot rollback transaction, connection 'default' not available
	at org.javalite.activejdbc.DB.rollbackTransaction(DB.java:587)
	at org.javalite.activejdbc.Base.rollbackTransaction(Base.java:296)
	at com.unrc.app.BuildingSpec.after(BuildingSpec.java:22)
</error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.CitySpec" time="0.015">
    <error message="com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database &apos;inmoapp_development_test&apos;" type="org.javalite.activejdbc.InitException"><![CDATA[org.javalite.activejdbc.InitException: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database 'inmoapp_development_test'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:812)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3269)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1182)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2670)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at org.javalite.activejdbc.DB.open(DB.java:64)
	at org.javalite.activejdbc.Base.open(Base.java:51)
	at com.unrc.app.CitySpec.before(CitySpec.java:16)
]]></error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.CitySpec" time="0.016">
    <error message="Cannot rollback transaction, connection &apos;default&apos; not available" type="org.javalite.activejdbc.DBException">org.javalite.activejdbc.DBException: Cannot rollback transaction, connection 'default' not available
	at org.javalite.activejdbc.DB.rollbackTransaction(DB.java:587)
	at org.javalite.activejdbc.Base.rollbackTransaction(Base.java:296)
	at com.unrc.app.CitySpec.after(CitySpec.java:22)
</error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.RealEstateSpec" time="0.007">
    <error message="com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database &apos;inmoapp_development_test&apos;" type="org.javalite.activejdbc.InitException"><![CDATA[org.javalite.activejdbc.InitException: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database 'inmoapp_development_test'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:812)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3269)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1182)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2670)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at org.javalite.activejdbc.DB.open(DB.java:64)
	at org.javalite.activejdbc.Base.open(Base.java:51)
	at com.unrc.app.RealEstateSpec.before(RealEstateSpec.java:16)
]]></error>
  </testcase>
  <testcase name="shouldValidateMandatoryFields" classname="com.unrc.app.RealEstateSpec" time="0.008">
    <error message="Cannot rollback transaction, connection &apos;default&apos; not available" type="org.javalite.activejdbc.DBException">org.javalite.activejdbc.DBException: Cannot rollback transaction, connection 'default' not available
	at org.javalite.activejdbc.DB.rollbackTransaction(DB.java:587)
	at org.javalite.activejdbc.Base.rollbackTransaction(Base.java:296)
	at com.unrc.app.RealEstateSpec.after(RealEstateSpec.java:22)
</error>
  </testcase>
</testsuite>